language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: JEEn8jovTK/GOTmApb6felnSH4nkZ74SEdXAbuWXRQbkFy/66nz2c4cjSHK7i3m1zASyq+P18Zc6mhlQeRXne3BQk8+gKdwOlcE6LaZt/LsEmX7IY2Mz1bCajT2sRvSsIGHyoODVxnJQn4++R2o4cXuxEsNn+8e/cpFOgCdU3/eCPmX5bWtJ+6xw6z0WDqYYm+Ym5rJVKtnhtVx1v0nKoW5GjF+UYylK0Np81/gKRNjyKj+/5IdXOuVGDFsoW/RWYW7YEwIrlE+QwuJw4DdgOzcldYgG/fxlHy3iVuSr9ynvdTVYGZCltIN1wtyGz0G0W3Azlkh+brxjEczYS08eDMRPAzyKZQTMQTUj3uvPUWtJHQm2j4qQmVvh5i039LOdBZcFcfuTZC2D+hLDE4g215agzUT9d82vJcrPj1tZG2/odHXX7oqaSphwHFB8WIHi+FiE7enZKHf/oZlns+PBi/QUykfXRIKKrNdIKY5c2onrt9gCCpZSOrghrAgDHIY7UN0E/yUXLS8/2FIRv/f+JCsdRj0U1sVo/1rJEC8QtxYeZpL5ty97WVo9d0Q1JndGA0S8xomujX9s6o1Uisdg7ygQK44k5FX7GD91hrJg+LVrtDR85klHIZagZsoVYNIQ7VIAoLvlFakGCILNuUxytE2OGXyrVtUF8O8MFDxLxFg=
