# jekyll configuration

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font-awesome

# Assign a default content for your site's
title:            DISID Blog
description:      Come Learn and Share
logo:             logo_DISID.png
logo-negative:    logo-disid-white.png

# Assign a default image for your site's header and footer
default_bg:       dotted.png

# Assign a default properties for your site
disqus_shortname: disid
comments:         true
search:           true
share:            true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:              200
# Turn on or off the fin animations in the header and footer
triangleheader:   false
animated_fins:    false
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://blog.disid.com
#url:             http://localhost:4000
url-external:    http://www.disid.com/

# Color settings (hex-codes without the leading hash-tag)
# primary_rgb: "59,139,186" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
color:
  primary: 366180
  secondary: 414A52
  secondary-dark: 002436
  light: 7AE2DE

# Owner/author information
owner:
  name:           DISID Corporation
  avatar:         favicon_DISID.png
  email:          info@disid.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Software solutions provider
  # Social networking links used in footer. Update and remove as you like.
  twitter:        disid_corp
  facebook:       DISIDCorp
  github:         DISID
  instagram:      disid_corp
  linkedin:       company/disid
  skype:          skype:disid_info?call
  phone:          +34 963 516 309

# For Google Authorship https://plus.google.com/authorship
#google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-1393802-6
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/disid_corp
  - title: facebook
    url: https://www.facebook.com/DISIDCorp/
  - title: github
    url: https://github.com/DISID
  - title: linkedin
    url: https://www.linkedin.com/company/disid

# Postal address (add as many lines as necessary). Shown in footer on Contact section.
address:
  - lines:
    - C/ San Vicente Mártir, 84 - 5A Valencia
    - CP 46002, Spain
email: info@disid.com
tel: (+34) 963 516 309

#
#Multilanguage
#

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: /es
    values:
      lang: es
t:
  en:
    title: "DISID, Be software"
    description: "We are a software engineering company specialized in Java technology."
    intro-lead-in: "Be Software"
    intro-heading: "We are your best choice"
    learn-more: Learn more
    close: Close
    footer-text: Sociedad Limitada 2013 CC BY-NC-SA 3.0 ES | Developed with Jekyll & Bootstrap
    suscribe: Subscribe to stay in the loop
    suscribe-button: Subscribe me!
    contact: Drop us a line
    technologies:
      section-heading: "Our Know-how"
      description: We like to provide technological solutions focused on what really matters to the business and developed on a daily basis. Select the most appropriate technology and tools for the development of each solution. Our base in Java, Spring and always working in a collaborative and evolving the OpenSource, we can offer a solution tailored to what you really need.
    services:
#      section-heading: "Our solutions"
#      section-subheading: "Solutions to and from any device."
    projects:
      section-heading: "Last Projects"
      description: "Find out which technologies move us and what R&D projects motivate us.
      Always on open source, we fix, improve and share our work into the core of the open platforms we use: Liferay, gvNIX, Spring, Spring Roo and gvSIG.
      An active and continued collaboration."
  es:
    title: "DISID, Be Software"
    description: "We are a software engineering company specialized in Java technology."
    intro-lead-in: "Be Software"
    intro-heading: "Nosotros somos tu mejor elección"
    learn-more: Saber más
    close: Cerrar
    footer-text: Sociedad Limitada 2013 CC BY-NC-SA 3.0 ES | Sitio web desarrollado con Jekyll & Bootstrap
    suscribe: Suscríbete para mantenerte informado de nuestras noticias
    suscribe-button: ¡Apúntame!
    contact: Queremos escucharte
    technologies:
      section-heading: "Nuestro soporte para el desarrollo"
      description: Nos gusta facilitar soluciones tecnológicas centradas en lo realmente importante para el negocio y desarrolladas en la base del día a día. Seleccionamos la tecnología y herramientas más apropiadas para el desarrollo de cada solución. Nuestra base en Java, Spring y siempre trabajando en un entorno colaborativo y en constante evolución del OpenSource, nos permite ofrecerte una solución ajustada a lo que realmente necesitas.
    services:
#      section-heading: "Nuestras soluciones"
#      section-subheading: "Soluciones desde y para cualquier dispositivo."
    projects:
      section-heading: "Nuestros Proyectos"
      description: "Entérate de primera mano sobre qué tecnologías nos movemos y qué proyectos nos motivan.
      Siempre sobre código abierto, desarrollamos mejoras e implementaciones sobre nuestras plataformas de desarrollo Liferay, gvNIX, Spring Roo y gvSIG.
      Una participación activa y continuada."


# To include variable in liquid: {{ site.t[page.lang].labs.section-heading }}
# You can add translations group

# Links to include in top navigation
# For external links add external: true/false
links-site:
  en:
    solutions:
      title: Solutions
      url: "http://www.disid.com#solutions"
      external: true
    projects:
      title: Projects
      url: "http://www.disid.com#projects"
      external: true
    technologies:
      title: Technologies
      url: "http://www.disid.com#technologies"
      external: true
    blog:
      title: Blog
      url: /
      icon: home
    contact:
      title: Contact
      url: "http://www.disid.com#contact"
      external: true
  es:
    solutions:
      title: Soluciones
      url: "http://www.disid.com/es/#solutions"
      external: true
    projects:
      title: Projectos
      url: "http://www.disid.com/es/#projects"
      external: true
    technologies:
      title: Tecnologías
      url: "http://www.disid.com/es/#technologies"
      external: true
    blog:
      title: Blog
      url: "http://blog.disid.com/es/index.html"
    contact:
      title: Contacto
      url: "http://www.disid.com/es/#contact"
      external: true

linksextra:
  en:
    notice:
      title: Legal notice
      url: "http://www.disid.com/legal-notice"
      external: true
    cookies:
      title: Cookies
      url: "http://www.disid.com/cookies-policy"
      external: true
  es:
    notice:
      title: Aviso legal
      url: "http://www.disid.com/aviso-legal"
      external: true
    cookies:
      title: Cookies
      url: "http://www.disid.com/politica-de-cookies"
      external: true

links:
#  - title: Blog
#    url: /
#    icon: home
  - title: Featured posts
    url: /featured
    tooltip: Featured posts
  - title: Category Index
    url: /categories
    tooltip: Category index
  - title: Tags
    url: /tags

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    8
paginate_path: "page:num"


# multilingual config
# Info https://www.sylvaindurand.org/making-jekyll-multilingual/

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/es
    values:
      layout: default
      lang: es

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/
#permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://disid.github.io/disid-blog/'
  relativeLinks: 'http://disid.github.io/disid-blog/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "type"
        field:
          element: "select"
          label: "Select Post Type"
          placeholder: "Choose your type"
          options:
            - name: "Standard"
              value:
            - name: "Quote"
              value: quote
            - name: "Status"
              value: status
            - name: "Photo"
              value: photo
            - name: "Video"
              value: video
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Web-Development"
              value: webdevelopment
            - name: "Interesting"
              value: interesting
            - name: "Status"
              value: status
            - name: "Quotes"
              value: quotes
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "imagecredit"
        field:
          element: "text"
          label: "Image Credit"
          placeholder: "some guy"
      - name: "imagecreditlink"
        field:
          element: "text"
          label: "Credit link for the image"
          placeholder: "http://somewebsite.com"
      - name: "video"
        field:
          element: "text"
          label: "Insert Youtube Link"
          placeholder: "http://youtube.com/somevideo"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

